### ISSUE TITLE
Support for special characters?

### ISSUE THREAD

**Issue by vbgm** [VeliovGroup/flow-router#4]
Hi there, the original flow-router has a flaw with special characters - https://github.com/kadirahq/flow-router/issues/599
Some details and a workaround can be found here: https://forums.meteor.com/t/flowrouter-special-characters-encoding/30886

Is it fixed/planned to be fixed in the flow-router-extra?  In particular I am interested in commas as they are valid URL characters, but are encoded by flow router to '%2C'.

**Comment by dr-dimitru** [comment]
@vblagomir sure.
Going to update this package for latest meteor compatibility, hope your suggestion will fit into this update

**Comment by dr-dimitru** [comment]
@vblagomir 

Turns out you wouldn't have characters like comma or "at" symbol, but unicode symbols like "そししきききちち" will work fine in further release.

I'm not saying it son possible, but this will use unexpected behavior in some browsers

Will this work for you?

**Comment by dr-dimitru** [comment]
@vblagomir 
Partially fixed in [`v2.12.7`](https://github.com/VeliovGroup/flow-router/releases/tag/2.12.7) let me know if it works for you

**Comment by vbgm** [comment]
Thank you @dr-dimitru for the feedback. 

In my specific case I store selected items in routes like this:
'app.com/items?selected=id1,id2,id3'

And since by default FlowRouter dont render commas, on every route change I have to manually parse the string and convert %20C to a comma. And then inject the new route to browser history.

So far there was no need for me to have non latin symbols in the routes, but maybe it helps someone else. 

Could you please elaborate on what kind of unexpected behavior and which browsers the commas might affect?

**Comment by dr-dimitru** [comment]
@vblagomir 

This is fixed in latest release mentioned above.

So, url `app.com/items?selected=id1,id2,id3` will appear as `app.com/items?selected=id1%2Cid2%2Cid3` and `FlowRouter.getQueryParam('selected')` will return `id1,id2,id3`

Same will work for param: `app.com/items/selected/id1,id2,id3` (route mask: `/items/selected/: selected `) will appear as `app.com/items/selected/id1%2Cid2%2Cid3` and `FlowRouter.getParam('selected')` will return `id1,id2,id3`

Please test it on your end, and let me know if it will work for you

**Comment by vbgm** [comment]
@dr-dimitru I am still on original flow-router, and so far this was the main feature I wanted from it to be improved (and of course the maintenance, which is great to see here).

However what you say seem still not fixing the problem, as I understand. Because it is not about  getQueryParam() function (as I remember I get the correct comma separated values from original flow-router getQueryParam()), it is about having the **url path in browser** to show commas instead of the %2C symbols, so that people when sending to each other some application's links would be able to copy paste the link and read the content, because this:

`app.com/items?selected=id1,id2,id3`

is quickly readable as there are 3 items selected, while this:

`app.com/items?selected=id1%2Cid2%2Cid3`

shows that something is selected, and whereas works with the app, is not readable by humans.

**Comment by dr-dimitru** [comment]
[RFC 3968](https://tools.ietf.org/html/rfc3986) tells us what all non-letter symbols must be encoded, only except `.-_` symbols.

If we will alter this behavior - correct handling by browsers is not guaranteed.
Yes, new browsers supports non-encoded symbols or will do it for you, but this doesn't means we could step away from standardization.

**Comment by vbgm** [comment]
Well, you probably referring to paragraph 2.2 where commas are treated as reserved characters with a purpose of delimiters and that 'may' (or may not) be used in future. Then probably it is just my specific requirement and I would need to stick to my workaround of changing the browser history, even though it is not 100% 'correct' solution, but it is human readable and to me it is more important than hypothetical 'correctness'.

And before closing this ticket, one should probably test the unicode characters then..

**Comment by dr-dimitru** [comment]
I've added unicode symbols and special chars to the [test-app](https://github.com/VeliovGroup/Flow-Router-Demos/blob/master/flow-router-meta/client/demo.jade#L15)

You can download it and run tests on your end

**Comment by dr-dimitru** [comment]
And commas used as special characters at multi-host urls, like [Mongo's replicaset](https://docs.mongodb.com/manual/reference/connection-string/) - hosts listed via commas

**Comment by vbgm** [comment]
I just wonder how come mongo is allowed to use them and flow-router not? ;-)

**Comment by dr-dimitru** [comment]
Doesn't matter, what if tomorrow Chrome will announce support of build-in "Mongo-Browser" or some 3rd party package which works via browser. And it will start interpret non-encoded commas as host-separation symbol? There is uncountable variations of software+hardware+unpredictable_user_actions that why there its standards, like `RFC 3968`. And we should follow it.

**Comment by vbgm** [comment]
Ok, got it.
