### ISSUE TITLE
Using waitOn for async imports may break styles

### ISSUE THREAD

**Issue by janat08** [VeliovGroup/flow-router#49]
- Give an expressive description of what is went wrong: 
https://github.com/Blockrazor/blockrazor/issues/1352
  - Version of `flow-router-extra` you're experiencing this issue 
current latest (the one that implemented fast render)
  - Version of `Meteor` you're experiencing this issue 
1.6.0
  - Browser name and its version (Chrome, Firefox, Safari, etc.)?
chrome
  - Platform name and its version (Win, Mac, Linux)? 
windows
  - If you're getting an error or exception, please provide its full stack-trace as plain-text or screenshot

**Comment by dr-dimitru** [comment]
@janat08 https://github.com/Blockrazor/blockrazor/issues/1352#issuecomment-385385425 is closed, I'm confused. Is it solved?

**Comment by janat08** [comment]
Yes it was solved before I opened this issue, using async and imports fixed it instead of waitOn hook.

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.

**Comment by janat08** [comment]
the navigation error wasn't about the waitOn hook, but the rest of it is a bug though. I imagine if you just await import it won't eagerly load rest of the bundle on window load?

**Comment by janat08** [comment]
or rather making the imports part of the initialization step.

**Comment by dr-dimitru** [comment]
@janat08 thank you for coming back with it.

 1. I still can't understand where issue is;
 2. Small reproduction will help a lot (*speak code*).

**Comment by janat08** [comment]
I'll not look for reproduction, since judging by how the app doesn't begin loading pages/templates between navigations I suppose using async/await is okay.

**Comment by janat08** [comment]
It's possible that we were depending on SASS variables defined by a theme that was dynamically imported under different file/route or something, so indeed this may not be so much a bug.

**Comment by dr-dimitru** [comment]
@janat08 Dynamically importing styles might be tricky.
But you should be good as long as you importing `.js` file dynamically, where `.sass` imported statically.
